jobs:
  - job: "runCheckov"
    displayName: "Test"
    steps:
      - bash: |
          docker pull bridgecrew/checkov
        workingDirectory: $(System.DefaultWorkingDirectory)
        displayName: "Pull > bridgecrew/checkov"

      - bash: |
          docker run --volume  $(pwd):/tf bridgecrew/checkov --directory /tf --output junitxml --soft-fail >  $(pwd)/CheckovReport.xml
        workingDirectory: $(System.DefaultWorkingDirectory)
        displayName: "Run > checkov"

      - task: PublishTestResults@2
        displayName: "Publish test results"
        inputs:
          testRunTitle: "Checkov test Results"
          failTaskOnFailedTests: false
          testResultsFormat: "JUnit"
          testResultsFiles: "CheckovReport.xml"
          searchFolder: "$(System.DefaultWorkingDirectory)"
